spring:
  datasource: #数据库地址
    url: jdbc:mysql://60.205.210.162:3306/tcy?serverTimezone=UTC
    username: root
    password: 46Bcd2d066c5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: #对日期格式转换
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:  #服务端口号
  port: 8181